import { NextRequest, NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { createServiceClient } from "@/lib/supabase";

export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  const { userId } = await auth();
  if (!userId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const db = createServiceClient();

  const { data: job } = await db
    .from("jobs")
    .select("*")
    .eq("id", params.id)
    .eq("user_id", userId)
    .single();

  if (!job || job.status !== "done") {
    return NextResponse.json({ error: "Job not found or not ready" }, { status: 404 });
  }

  const { data: sections } = await db
    .from("job_sections")
    .select("*, job_steps(*)")
    .eq("job_id", params.id)
    .order("order_index");

  const lines: string[] = [];
  lines.push(`# ${job.title}`);
  lines.push("");

  if (job.description) {
    lines.push(job.description);
    lines.push("");
  }

  if (job.estimated_time) {
    lines.push(`**Estimated Time:** ${job.estimated_time}`);
    lines.push("");
  }

  lines.push("---");
  lines.push("");

  let globalStepNum = 1;

  for (const section of sections ?? []) {
    lines.push(`## ${section.title}`);
    lines.push("");

    const steps = (section as unknown as { job_steps: Array<{ title: string; description: string; note: string | null; order_index: number }> }).job_steps ?? [];
    const sorted = [...steps].sort((a, b) => a.order_index - b.order_index);

    for (const step of sorted) {
      lines.push(`### Step ${globalStepNum}: ${step.title}`);
      lines.push("");
      lines.push(step.description);
      if (step.note) {
        lines.push("");
        lines.push(`> **Note:** ${step.note}`);
      }
      lines.push("");
      globalStepNum++;
    }
  }

  lines.push("---");
  lines.push("");
  lines.push("## Checklist");
  lines.push("");

  globalStepNum = 1;
  for (const section of sections ?? []) {
    const steps = (section as unknown as { job_steps: Array<{ title: string; order_index: number }> }).job_steps ?? [];
    const sorted = [...steps].sort((a, b) => a.order_index - b.order_index);
    for (const step of sorted) {
      lines.push(`- [ ] Step ${globalStepNum}: ${step.title}`);
      globalStepNum++;
    }
  }

  lines.push("");
  lines.push(`---`);
  lines.push(`*Generated by VidManual — vidmanual.com*`);

  const markdown = lines.join("\n");
  const filename = `${job.title.replace(/[^a-z0-9]/gi, "_").toLowerCase()}_sop.md`;

  return new NextResponse(markdown, {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
  });
}
